apiVersion: apps/v1
kind: Deployment
metadata:
  name: aioqubeneties
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aioqubeneties
  template:
    metadata:
      labels:
        app: aioqubeneties
    spec:
      containers:
      - name: aioqubeneties
        image: aioqubeneties:latest
        ports:
        - containerPort: 80
