apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-k8s
  labels:
    app: helloworld-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-k8s
  template:
    metadata:
      labels:
        app: helloworld-k8s
    spec:
      containers:
      - name: helloworld-k8s
        image: "paulbouwer/hello-kubernetes:1.10"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-k8s-svc
spec:
  selector:
    app: helloworld-k8s
  ports:
  - port: 83
    targetPort: 8080
  type: LoadBalancer
