name: Greetings

on: 
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-messag: Hello! 👋 Thanks for opening an issue. We'll take a look as soon as possible."
          pr-message: "Thanks for your PR! 🚀 It will be reviewed soon."
